# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
  labels:   
    partof: postgres-keycloak   
spec:
  selector:
    app: postgres-keycloak
  type: LoadBalancer
  ports:
    - name: postgres-keycloak-ports
      port: 5432
      targetPort: 5432
      protocol: TCP
