# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
  labels:   
    partof: postgres-keycloak

## headless Service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresk-ports
      port: 5432
      targetPort: postgresk-ports
      protocol: TCP
  selector:
    app: postgres-keycloak
