apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-keycloak-stateful-set
  namespace: keycloak
spec:
  serviceName: postgres-keycloak-service
  selector:
    matchLabels:
      app: postgres-keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-keycloak
        name: postgresql
        component: database
        part-of: keycloak
        environment: dev
    spec:
      containers:
        - name: postgres-keycloak
          ## https://github.com/docker-library/docs/blob/master/postgres/README.md#image-variants
          image: postgres:latest # either Debian(default) or add 'postgres:latest-alpine'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-keycloak-db
              mountPath: /data
          env:
            ## https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-keycloak-credentials-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-keycloak-credentials-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-keycloak-configmap
                  key: POSTGRES_DB
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: postgres-keycloak-configmap
                  key: PGDATA
          ##- name: POSTGRES_INITDB_ARGS
          ##- name: POSTGRES_INITDB_WALDIR
          ##- name: POSTGRES_HOST_AUTH_METHOD
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          ports:
            - name: pgsql-tcp-port
              containerPort: 5432
              protocol: TCP
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - su - postgres -c "pg_ctl stop -m fast"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - exec pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 7
          securityContext:
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgres-keycloak-db
      spec:
        ##storageClassName: linode-block-storage-retain
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
