apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
  labels:
    part-of: postgres-keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: pgsql-tcp-port
      port: 5432
      targetPort: pgsql-tcp-port
      protocol: TCP
  selector:
    app: postgres-keycloak