apiVersion: v1
kind: ConfigMap
metadata:
  name: postal-rabbitmq-config
  namespace: postal
  labels:        
    partof: postal
    created-by: Ed-Mar
stringdata:  
  ##RABBITMQ_HOST
  rabbitmq-host: postal-rabbitmq
  ##RABBITMQ_VHOST
  rabbitmq-vhost: /postal
  