version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"

    env_file:
        - ../config/postgres.env

    volumes:
      - ./db-models/:/var/lib/postgresql/models/


    # TODO Need to write a readiness and helath check
    # TODO Need to create all the service users
